routes/web.php
<?php


use Illuminate\Support\Facades\Route;
use App\Http\Controllers\BlogController;
use App\Http\Controllers\LikeController;
use App\Http\Controllers\CommentController;
use App\Http\Controllers\ProfileController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

/* Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth', 'verified'])->name('dashboard'); */

Route::middleware('auth')->group(function () {
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');


    Route::get('/dashboard/{search?}', [BlogController::class, 'show_all_blogs'])->name('dashboard');
    Route::resource('blog', BlogController::class);
    Route::resource('likes', LikeController::class);
    Route::resource('comments', CommentController::class);
    

});

require __DIR__.'/auth.php';

app/Models/Blog.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Blog extends Model
{
    use HasFactory;

    public function blog_comments()
    {
      return $this->hasMany('App\Models\Comment','blog_id','id');
    }

    public function blog_likes()
    {
      return $this->hasMany('App\Models\Like','blog_id','id');
    }
}

app/Http/Controllers/BlogController.php
<?php

namespace App\Http\Controllers;

use App\Models\Tag;
use App\Models\Blog;
use App\Models\User;
use App\Models\Category;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Storage;


class BlogController extends Controller
{
    /**
     * Display a listing of the blogs.
     */
    public function index()
    {
        
        $blogs = Blog::with('blog_comments')->where('added_by',Auth::user()->id)->orderBy('id','desc')->get();  
        return view('blog.list', ['blogs' => $blogs]);
    }

    /**
     * Display a listing of the all user's blogs.
     */
    public function show_all_blogs(Request $request)
    {
        $categoryCount = Category::count();
        if ($categoryCount == 0)
        {
            $newCategory = new Category;
            $newCategory->category = "Travel";
            $newCategory->save();

            $newCategory = new Category;
            $newCategory->category = "Food";
            $newCategory->save();
        }
        $search = $request->search;
        if ($search) 
        {   
            $blogs = Blog::with('blog_comments')->where(function ($query) use($search) {
                $query->where('title', 'like', '%' . $search . '%')
                   ->orWhere('place', 'like', '%' . $search . '%')
                   ->orWhere('categories', 'like', '%' . $search . '%')
                   ->orWhere('tags', 'like', '%' . $search . '%');
              })->orderBy('id','desc')->paginate(5);  
        } else 
        {
            $blogs = Blog::with('blog_comments')->orderBy('id','desc')->paginate(5);  
        }
        


        return view('dashboard', ['blogs' => $blogs]);
    }

    /**
     * Show the form for creating a new blog.
     */
    public function create()
    {
        return view('blog.create');
    }

    /**
     * Store a newly created blog in storage.
     */
    public function store(Request $request)
    {
      
        $request->validate([
            'title' => 'required|string',
            'description' => 'required',
            'place' => 'required|string',
            /* 'image' => 'mimes:jpeg,jpg,png,|max:20480', */
        ]);

      /*   $newBlog = Blog::create($request->all());

        return redirect(route('blog.index'));

        */


        $newBlog = new Blog;
        $newBlog->title = $request->title;
        $newBlog->description = $request->description;
        $newBlog->place = $request->place; 
        $newBlog->links = $request->links;
        $newBlog->added_by = $request->added_by;
        
        if ($request->categories) 
        {
            $newBlog->categories = $request->categories;
        }
        if ($request->tags) 
        {
            $newBlog->tags = $request->tags;

            $tagList = explode(',', $request->tags);
            foreach ($tagList as $tag)
            {
                $isTagExists = Tag::where('tag', trim($tag))->exists();
                if (!$isTagExists)
                {
                    Tag::create([
                        'tag'=> trim($tag),
                    ]);
                }
                
            }
        }
      
        if ($request->file('image'))
        {
            $file = $request->image;
            $filename = uniqid(). '.' .$request->file('image')->getClientOriginalExtension();
            //uniqid() is php function to generate uniqid but you can use time() etc.
    
            $path = "public/Files/Images/";
            Storage::disk('local')->put($path.$filename,file_get_contents($file));
            $link = 'Files/Images/'.$filename;
            $newBlog->image = $link;
        }
        

        if ($newBlog->save())
        {
            //echo asset('storage/'.$event->file_link);
            
            //session()->flashMessage('check', 'Blog Created successfully!', 'success');

            return redirect()->route('blog.index');
        }

    }

    /**
     * Display the specified blog.
     */
    public function show(Blog $blog)
    {
        
        return view('blog.view', ['blog'=> $blog]);
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Blog $blog)
    {
        return view('blog.edit', compact('blog'));
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, Blog $blog)
    {
       
        
       /*  $request->validate([
            'title'=> 'required',
            'description'=> 'required',
            'place' => 'required',

        ]);
        $blog->title = $request->title;
        $blog->description = $request->description;
        $blog->place = $request->place;
        $blog->links = $request->links;
        $blog->save(); */
        
        

        return redirect()->route('blog.edit', $blog->id)->with('success','Blog updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Blog $blog)
    {
        $blog->delete();

        return redirect()->route('blog.index');
    }
}

resources/views/blog/create.blade.php
@extends('layouts.app')

@section('content')  
<section class="section">
    <div class="container">
        <div class="row no-gutters-lg">
            <div class="col-12">
                <h2 class="section-title">My Blogs</h2>
                
            </div>
            <div class="col-lg-8 mb-5 mb-lg-0">
                <div class="row">
                    <div class="col-md-12">	
                         <form action="{{ route('blog.store') }}" method="post" enctype="multipart/form-data">
                            {{ csrf_field() }}
                            <input type="hidden" name="active" value="1">
                            <input type="hidden" name="added_by" value="{{Auth::user()->id}}">
                            <div class="row">
                                <div class="col-lg-6">
                                    <div class="form-group {{ $errors->has('title') ? 'has-error' : '' }}">
                                        <label for="nome">Title</label>
                                        <input type="text" name="title" class="form-control" placeholder="title" required="" value="{{ old('title') }}" autofocus>
                                        @if($errors->has('title'))
                                            <span class="help-block">
                                                <strong>{{ $errors->first('title') }}</strong>
                                            </span>
                                        @endif
                                    </div>
                                </div>
                                
                                <div class="col-lg-6">
                                    <div class="form-group {{ $errors->has('place') ? 'has-error' : '' }}">
                                        <label for="nome">place</label>
                                        <input type="text" name="place" class="form-control" placeholder="place" minlength="6" required="">
                                        @if($errors->has('place'))
                                            <span class="help-block">
                                                <strong>{{ $errors->first('place') }}</strong>
                                            </span>
                                        @endif
                                    </div>
                                </div>
                                <div class="col-lg-6">
                                    <div class="form-group {{ $errors->has('links') ? 'has-error' : '' }}">
                                        <label for="nome">Link</label>
                                        <input type="text" name="links" class="form-control" placeholder="links">
                                        @if($errors->has('links'))
                                            <span class="help-block">
                                                <strong>{{ $errors->first('links') }}</strong>
                                            </span>
                                        @endif
                                    </div>
                                </div>

                                <div class="col-lg-6">
                                    <div class="form-group {{ $errors->has('categories') ? 'has-error' : '' }}">
                                        <label for="nome">Category</label>
                                        {{-- <input type="text" name="category" class="form-control" placeholder="category"> --}}
                                        <select name="categories" class="form-control" id="">
                                            @foreach(categories() as $category)
                                            <option value="{{$category->category}}">{{$category->category}}</option>
                                            @endforeach
                                        </select>
                                        @if($errors->has('categories'))
                                            <span class="help-block">
                                                <strong>{{ $errors->first('categories') }}</strong>
                                            </span>
                                        @endif
                                    </div>
                                </div>

                                <div class="col-lg-6">
                                    <div class="form-group {{ $errors->has('tags') ? 'has-error' : '' }}">
                                        <label for="name">Tags(Add coma between tags)</label>
                                        <input type="text" name="tags" class="form-control" placeholder="tags">
                                        @if($errors->has('tags'))
                                            <span class="help-block">
                                                <strong>{{ $errors->first('tags') }}</strong>
                                            </span>
                                        @endif
                                    </div>
                                </div>
                               
                               
                                
    
                                <div class="col-lg-6">
                                    <div class="form-group {{ $errors->has('image') ? 'has-error' : '' }}">
                                        <label for="nome">image</label>
                                        <input type="file" name="image" class="form-control" >
                                        @if($errors->has('image'))
                                            <span class="help-block">
                                                <strong>{{ $errors->first('image') }}</strong>
                                            </span>
                                        @endif
                                    </div>
                                </div>
    
                                
                                <div class="col-lg-12">
                                    <div class="form-group {{ $errors->has('description') ? 'has-error' : '' }}">
                                        <label for="nome">Description</label>
                                        <textarea name="description" class="form-control" placeholder="description" required=""  cols="50" rows="10">{{ old('description') }}</textarea>
                                        {{-- <input type="text" name="description" class="form-control" placeholder="description" required="" value="{{ old('description') }}"> --}}
                                        @if($errors->has('description'))
                                            <span class="help-block">
                                                <strong>{{ $errors->first('description') }}</strong>
                                            </span>
                                        @endif
                                    </div>
                                </div>
                                
                                
                                <div class="col-lg-6"></div>
                                <div class="col-lg-6">
                                   <button type="submit" class="btn btn-primary float-right"><i class="fa fa-fw fa-plus"></i> Add</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>

            @include('layouts.right_navigation')
        </div>
    </div>
</section>
@endsection

resources/views/blog/edit.blade.php
@extends('layouts.app')

@section('content')  
<section class="section">
    <div class="container">
        <div class="row no-gutters-lg">
            <div class="col-12">
                <h2 class="section-title">My Blogs</h2>
                
            </div>
            <div class="col-lg-8 mb-5 mb-lg-0">
                <div class="row">
                    <div class="col-md-12">	
                         <form action="{{ route('blog.update',$blog->id) }}" method="post" enctype="multipart/form-data">
                            {{ csrf_field() }}
                            <input type="hidden" name="_method" value="put">
                            <input type="hidden" name="active" value="1">
                            <input type="hidden" name="added_by" value="{{Auth::user()->id}}">
                            <div class="row">
                                <div class="col-lg-6">
                                    <div class="form-group {{ $errors->has('title') ? 'has-error' : '' }}">
                                        <label for="nome">Title</label>
                                        <input type="text" name="title" class="form-control" maxlength="30" minlength="4" placeholder="title" required="" value="{{ $blog->title }}" autofocus>
                                        @if($errors->has('title'))
                                            <span class="help-block">
                                                <strong>{{ $errors->first('title') }}</strong>
                                            </span>
                                        @endif
                                    </div>
                                </div>
                                
                                <div class="col-lg-6">
                                    <div class="form-group {{ $errors->has('place') ? 'has-error' : '' }}">
                                        <label for="nome">place</label>
                                        <input type="text" name="place" class="form-control" placeholder="place" minlength="6" required="" value="{{$blog->place}}">
                                        @if($errors->has('place'))
                                            <span class="help-block">
                                                <strong>{{ $errors->first('place') }}</strong>
                                            </span>
                                        @endif
                                    </div>
                                </div>
                                <div class="col-lg-6">
                                    <div class="form-group {{ $errors->has('links') ? 'has-error' : '' }}">
                                        <label for="nome">Link</label>
                                        <input type="text" name="links" class="form-control" placeholder="links" value="{{$blog->links}}">
                                        @if($errors->has('links'))
                                            <span class="help-block">
                                                <strong>{{ $errors->first('links') }}</strong>
                                            </span>
                                        @endif
                                    </div>
                                </div>
                               
                               
                                
    
                                {{-- <div class="col-lg-6">
                                    <div class="form-group {{ $errors->has('image') ? 'has-error' : '' }}">
                                        <label for="nome">image</label>
                                        <input type="file" name="image" class="form-control" >
                                        @if($errors->has('image'))
                                            <span class="help-block">
                                                <strong>{{ $errors->first('image') }}</strong>
                                            </span>
                                        @endif
                                    </div>
                                </div> --}}
    
                                
                                <div class="col-lg-12">
                                    <div class="form-group {{ $errors->has('description') ? 'has-error' : '' }}">
                                        <label for="nome">Description</label>
                                        <textarea name="description" class="form-control" placeholder="description" required=""  cols="50" rows="10">{{$blog->description}}</textarea>
                                        {{-- <input type="text" name="description" class="form-control" placeholder="description" required="" value="{{ old('description') }}"> --}}
                                        @if($errors->has('description'))
                                            <span class="help-block">
                                                <strong>{{ $errors->first('description') }}</strong>
                                            </span>
                                        @endif
                                    </div>
                                </div>
                                
                                
                                <div class="col-lg-6"></div>
                                <div class="col-lg-6">
                                   <button type="submit" class="btn btn-primary float-right"><i class="fa fa-fw fa-plus"></i> Update</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>

            @include('layouts.right_navigation')
        </div>
    </div>
</section>
@endsection

resources/views/blog/list.blade.php
@extends('layouts.app')

@section('content')  
<section class="section">
    <div class="container">
        <div class="row no-gutters-lg">
            <div class="col-12">
                <h2 class="section-title">My Blogs</h2>
                <a href="{{ route('blog.create') }}" class="btn btn-sm btn-outline-primary float-right">New Blog</a>
            </div>
            <div class="col-lg-8 mb-5 mb-lg-0">
                <div class="row">
                  
                    @foreach ($blogs as $item)
                    <div class="col-md-6 mb-4">
                        <article class="card article-card article-card-sm h-100">
                            <a href="article.html">
                                <div class="card-image">
                                    <div class="post-info"> <span class="text-uppercase">{{$item->created_at}}</span>
                                        
                                    </div>
                                    <img loading="lazy" decoding="async" src="{{ asset('storage/'.$item->image) }}" alt="Post Thumbnail" class="w-100">
                                </div>
                            </a>
                            <div class="card-body px-0 pb-0">
                            {{-- <ul class="post-meta mb-2">
                                <li> <a href="#!">travel</a></li>
                                <li> <a href="#!">travel</a></li>
                            </ul> --}}
                            <h2><a class="post-title" href="{{ route('blog.show', $item->id) }}">{{$item->title}}</a>
                            </h2>
                            <p class="card-text">{{$item->description}}</p>
                            <div class="content">
                               <a class="read-more-btn" href="{{ route('blog.show', $item->id) }}">Read Full Article</a>
                               
                                <a  class="float-right m-2" title="Delete {{ $item->title}}" data-toggle="modal" data-target="#modal-delete-{{ $item->id }}">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash text-danger   " viewBox="0 0 16 16">
                                        <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5m2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5m3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0z"/>
                                        <path d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4zM2.5 3h11V2h-11z"/>
                                    </svg>
                                </a>  
                                <a class="float-right m-2" href="{{ route('blog.edit', $item->id) }}">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-square text-primary" viewBox="0 0 16 16">
                                    <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
                                    <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5z"/>
                                    </svg>
                                </a>
                            </div>
                            </div>
                        </article>
                      </div>

                      <div class="modal fade" id="modal-delete-{{ $item->id }}">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">×</span>
                                    </button>
                                    <h4 class="modal-title"><i class="fa fa-warning"></i> Caution!!</h4>
                                </div>
                                <div class="modal-body">
                                    <p>Do you really want to delete ({{ $item->title }}) ?</p>
                                </div>
                                
                                <form action="{{ route('blog.destroy', $item->id) }}" method="post" enctype="multipart/form-data">
                                    {{ method_field('DELETE') }}
                                    {{ csrf_field() }}

                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Cancel</button>
                                        <a href="#"><button type="submit" class="btn btn-danger"><i class="fa fa-trash"></i> Delete</button></a>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                    @endforeach
                    




                  <div class="col-12">
                    <div class="row">
                      <div class="col-12">
                        <nav class="mt-4">
                          <!-- pagination -->
                          <nav class="mb-md-50">
                            <ul class="pagination justify-content-center">
                              <li class="page-item">
                              <a class="page-link" href="#!" aria-label="Pagination Arrow">
                                  <svg xmlns="http://www.w3.org/2000/svg" width="26" height="26" fill="currentColor" viewBox="0 0 16 16">
                                  <path fill-rule="evenodd" d="M12 8a.5.5 0 0 1-.5.5H5.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L5.707 7.5H11.5a.5.5 0 0 1 .5.5z"/>
                                  </svg>
                              </a>
                              </li>
                              <li class="page-item active "> <a href="index.html" class="page-link">
                                  1
                              </a>
                              </li>
                              <li class="page-item"> <a href="#!" class="page-link">
                                  2
                              </a>
                              </li>
                              <li class="page-item">
                              <a class="page-link" href="#!" aria-label="Pagination Arrow">
                                  <svg xmlns="http://www.w3.org/2000/svg" width="26" height="26" fill="currentColor" viewBox="0 0 16 16">
                                  <path fill-rule="evenodd" d="M4 8a.5.5 0 0 1 .5-.5h5.793L8.146 5.354a.5.5 0 1 1 .708-.708l3 3a.5.5 0 0 1 0 .708l-3 3a.5.5 0 0 1-.708-.708L10.293 8.5H4.5A.5.5 0 0 1 4 8z" />
                                  </svg>
                              </a>
                              </li>
                            </ul>
                          </nav>
                        </nav>
                      </div>
                    </div>
                  </div>
                </div>
              </div>

              @include('layouts.right_navigation')
            </div>
          </div>
        </section>


@endsection

@section('js')

@endsection

resources/views/blog/view.blade.php
@extends('layouts.app')

@section('content')  
<section class="section">
    <div class="container">
        <div class="row no-gutters-lg">
            <div class="col-12">
                <h2 class="section-title">View Full</h2>
                
            </div>
            <div class="col-lg-8 mb-5 mb-lg-0">
                <article>
                    <img loading="lazy" decoding="async" src="{{ asset('storage/'.$blog->image) }}" alt="Post Thumbnail" class="w-100">
                    <ul class="post-meta mb-2 mt-4">
                        <li>
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" style="margin-right:5px;margin-top:-4px" class="text-dark" viewBox="0 0 16 16">
                                <path d="M5.5 10.5A.5.5 0 0 1 6 10h4a.5.5 0 0 1 0 1H6a.5.5 0 0 1-.5-.5z" />
                                <path d="M3.5 0a.5.5 0 0 1 .5.5V1h8V.5a.5.5 0 0 1 1 0V1h1a2 2 0 0 1 2 2v11a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V3a2 2 0 0 1 2-2h1V.5a.5.5 0 0 1 .5-.5zM2 2a1 1 0 0 0-1 1v11a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V3a1 1 0 0 0-1-1H2z" />
                                <path d="M2.5 4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5H3a.5.5 0 0 1-.5-.5V4z" />
                            </svg> <span>{{date_format($blog->created_at,'d M, Y')}}</span>
                        </li>
                    </ul>
                    <h1 class="my-3" >{{$blog->title}}</h1>
                    <ul class="post-meta mb-4">
                        <li> <a >{{$blog->place}}</a>
                        </li>
                    </ul>
                    <h5 class="my-3">Category</h5>
                    <ul class="post-meta mb-4">
                        <li> <a >{{$blog->categories}}</a>
                        </li>
                    </ul>
                    <h5 class="my-3">Tags</h5>
                    <ul class="post-meta mb-4">
                        <li> <a >{{$blog->tags}}</a>
                        </li>
                    </ul>
                    <div class="content text-left">
                        <h1 id="heading">Description</h1>
                        <p>{{$blog->description}}</p>
                        
                        <!-- table of content -->
                        <h2 id="link">Link</h2>
                        <p><a href="{{$blog->links}}">{{$blog->links}}</a>
                        </p>
                      
                    </div>

                    
                </article>
              
            </div>

            @include('layouts.right_navigation')
        </div>
    </div>
</section>
@endsection